# Generated by Django 2.1.4 on 2018-12-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
