# Generated by Django 2.1.3 on 2018-12-06 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('remark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='回复人姓名')),
                ('text', models.TextField(blank=True, default='', verbose_name='回复内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('modelsid', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '回复内容',
                'db_table': 'articlereply',
                'ordering': ['-create_time'],
            },
        ),
    ]
