
DECLARE
    V_USERNAME   VARCHAR2(100);
    V_PASSWORD   VARCHAR2(100);
    V_DBNAME     VARCHAR2(100);
    V_DATASPACE  VARCHAR2(100);
    V_TEMPSPACE  VARCHAR2(100);
    V_FILEPATH   VARCHAR2(2000);
    V_SQLEXEC    VARCHAR2(2000);
    V_CNT        NUMBER;
BEGIN
    V_USERNAME   := UPPER('&1');
    V_PASSWORD   := '&2';
    V_DBNAME     := '&3';
    V_DATASPACE  := UPPER('&1')||UPPER('data');
    V_TEMPSPACE  := UPPER('&1')||UPPER('temp');
    -- get db_unique_name default : orcl
    SELECT NVL(VALUE, '') INTO V_DBNAME FROM V$PARAMETER WHERE NAME = 'db_unique_name';
    -- get db_create_file_dest default : /u01/app/oradata, eg : /u01/app/oradata/orcl/username
    SELECT NVL(VALUE, '') INTO V_FILEPATH FROM V$PARAMETER WHERE NAME = 'db_create_file_dest';
    IF V_FILEPATH IS NOT NULL THEN
        BEGIN
            V_FILEPATH := V_FILEPATH || '/' || V_DBNAME || '/' || LOWER(V_USERNAME) || '/';
        END;
    ELSE
        BEGIN
            V_FILEPATH := '';
        END;
    END IF;
    -- create tablespace
    SELECT COUNT(*) INTO V_CNT FROM DBA_TABLESPACES TS WHERE TS.TABLESPACE_NAME = V_DATASPACE;
    IF V_CNT = 0 THEN
        BEGIN
            V_SQLEXEC := '';
            V_SQLEXEC := V_SQLEXEC || 'CREATE TABLESPACE ' || V_DATASPACE || ' LOGGING DATAFILE ';
            V_SQLEXEC := V_SQLEXEC || CHR(39) || V_FILEPATH || V_DATASPACE || '01.DBF' || CHR(39) ||' SIZE 100M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 2048M ';
            V_SQLEXEC := V_SQLEXEC || 'EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO';
            EXECUTE IMMEDIATE V_SQLEXEC;
        END;
    END IF;
    --  create temporary tablespace
    SELECT COUNT(*) INTO V_CNT FROM DBA_TABLESPACES TS WHERE TS.TABLESPACE_NAME = V_TEMPSPACE;
    IF V_CNT = 0 THEN
        BEGIN
            V_SQLEXEC := '';
            V_SQLEXEC := V_SQLEXEC || 'CREATE TEMPORARY TABLESPACE ' || V_TEMPSPACE || ' TEMPFILE ';
            V_SQLEXEC := V_SQLEXEC || CHR(39) || V_FILEPATH || V_TEMPSPACE || '01.DBF' || CHR(39) ||' SIZE 100M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 1024M ';
            V_SQLEXEC := V_SQLEXEC || 'EXTENT MANAGEMENT LOCAL';
            EXECUTE IMMEDIATE V_SQLEXEC;
        END;
    END IF;
    -- create user
    SELECT COUNT(*) INTO V_CNT FROM DBA_USERS U WHERE U.USERNAME = V_USERNAME;
    IF V_CNT = 0 THEN
        BEGIN
            -- create user
            V_SQLEXEC := 'CREATE USER ' || V_USERNAME || ' IDENTIFIED BY "' || V_PASSWORD || '" DEFAULT TABLESPACE ' || V_DATASPACE || ' TEMPORARY TABLESPACE ' || V_TEMPSPACE;
            EXECUTE IMMEDIATE V_SQLEXEC;
        END;
    ELSE
        BEGIN
            -- drop user
            -- V_SQLEXEC := 'DROP USER ' || V_USERNAME || ' CASCADE';
            -- create user
            -- V_SQLEXEC := 'CREATE USER ' || V_USERNAME || ' IDENTIFIED BY "' || V_PASSWORD || '" DEFAULT TABLESPACE ' || V_DATASPACE || ' TEMPORARY TABLESPACE ' || V_TEMPSPACE;
            -- EXECUTE IMMEDIATE V_SQLEXEC;
            -- alter user
            V_SQLEXEC := 'ALTER USER ' || V_USERNAME || ' IDENTIFIED BY "' || V_PASSWORD || '" DEFAULT TABLESPACE ' || V_DATASPACE || ' TEMPORARY TABLESPACE ' || V_TEMPSPACE;
            EXECUTE IMMEDIATE V_SQLEXEC;
        END;
    END IF;
    -- grant permission for user
    BEGIN
        V_SQLEXEC := 'GRANT CONNECT, RESOURCE, EXP_FULL_DATABASE, IMP_FULL_DATABASE TO ' || V_USERNAME;
        EXECUTE IMMEDIATE V_SQLEXEC;
        V_SQLEXEC := 'GRANT CREATE ANY TABLE TO ' || V_USERNAME;
        EXECUTE IMMEDIATE V_SQLEXEC;
        V_SQLEXEC := 'GRANT CREATE ANY INDEX TO ' || V_USERNAME;
        EXECUTE IMMEDIATE V_SQLEXEC;
        V_SQLEXEC := 'GRANT CREATE ANY DIRECTORY TO ' || V_USERNAME;
        EXECUTE IMMEDIATE V_SQLEXEC;
        V_SQLEXEC := 'GRANT DEBUG CONNECT SESSION TO ' || V_USERNAME;
        EXECUTE IMMEDIATE V_SQLEXEC;
        V_SQLEXEC := 'GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO ' || V_USERNAME;
        EXECUTE IMMEDIATE V_SQLEXEC;
    END;
END;
/

EXIT;
