version: "2"

services:

  mysql:
    build: mysql
    container_name: mysql
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    image: redis:3.2-alpine
    container_name: redis
    restart: always
    ports:
        - 6379:6379

  nginx:
    image: nginx:1.12-alpine
    container_name: nginx
    restart: always
    privileged: true
    ports:
      - 8080:80
    volumes:
      - ./:/data/wwwroot
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - php

  php:
    image: php:5.6-fpm-alpine
    restart: always
    container_name: php
    volumes:
      - ./:/data/wwwroot
    links:
          - mysql
          - redis